language: node_js
before_install: 
  - gem update --system
  - gem install compass
  - npm install -g grunt-cli bower gulp
install:
  - npm install
  - bower install
#before_script: grunt build
script:
  - grunt build
after_success:
    "gulp deploy --user $FTP_USER --password $FTP_CRED --host $FTP_REMOTE_PATH"
    #"curl -T app/index.html -u $FTP_USER:$FTP_CRED $FTP_REMOTE_PATH"
